version: "3.3"

services:
  pyspark:
    build:
      context: .
    restart: on-failure
    volumes:
      - datasets:/src/datasets
    ports:
      - "4040:4040"

  s3:
    image: minio/minio
    restart: always
    environment:
      - MINIO_SERVER_PORT="9001"
      - MINIO_ACCESS_KEY=access_key
      - MINIO_SECRET_KEY=secret_key
    ports:
      - "100:100"
      - "9001:9001"
      - "9000:9000"
    command: server /data --console-address ":9001"
    volumes:
      - ./storage:/data

volumes:
  datasets:
  storage: